### ISSUE TITLE
Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by n8ventures** [shadoweG/ResolveRPC#1]
![image](https://user-images.githubusercontent.com/25238367/183848640-f7f9cf4e-af98-43a6-9946-70f9fa9a09cc.png)

I'm pretty new to Java but running it via CMD outputs this error. Opening it (via double-clicking the .jar file) doesn't show any window but I do see the process.

This is my Java version:
`java version "18.0.2" 2022-07-19`
`Java(TM) SE Runtime Environment (build 18.0.2+9-61)`
`Java HotSpot(TM) 64-Bit Server VM (build 18.0.2+9-61, mixed mode, sharing)`

**Comment by jacobbvfx** [comment]
It's normal, everything will work fine 😎.
